#!/usr/bin/env perl

use warnings;
use strict;

use Email::Sender::Simple qw(try_to_sendmail);
use Email::Simple;
use Email::Simple::Creator;
use Email::Sender::Transport::SMTP;
use Email::Sender::Transport::SMTP::TLS;

my $email_use_tls = 1;
my $email_use_ssl = 0;
my $email_port = 587;
my $email_smtp = 'smtp.gmail.com';
my $email_uid = 'StJamesPhoneTree@gmail.com';
my $email_pwd = unhidden( "15WP3LS3XUX0LXQ2");
my $emailSender = 'schdeulerTester';

use warnings;
use strict;

sub unhidden($);
sub sendEmail($$$$);

#main:
{
	sendEmail( 'gft@gftaylor.com', 'schedulerTest', 'Testing, dude', 'YO!');
}

#------------------------------------------------------------------------------
#  sub unhidden($)
#------------------------------------------------------------------------------
sub unhidden($)
{
 my $text = $_[0];
 $text =~ tr/a-z\-@A-Z!_0-9/0-9A-Z!_a-z\-@/;
 return( $text);
}

#------------------------------------------------------------------------------
#  sendEmail( $to, $from, $sub, $message)
#		This function uses the default email settings to send an email message.
#		The function returns a non-zero value if an error occurred.
#------------------------------------------------------------------------------
sub sendEmail($$$$)
{
 my ( $to, $from, $subj, $message) = @_;
 my $transport;

 if ( !defined( $emailSender))
 	{
	 $emailSender = $email_uid;
	}

 my $sender = (defined( $from)) ? $from : $emailSender;
 my $email = Email::Simple->create( 
									header => [
												To 		=> $to,
												From	=> $sender,
												Subject	=> $subj,
											  ],
									body => $message,
								  );

 if ( $email_use_tls)
 	{
	 $transport = Email::Sender::Transport::SMTP::TLS->new
	 	(
		 {
		 host => $email_smtp,
		 port => $email_port,
		 username => $email_uid,
		 password => $email_pwd,
		 helo => 'bgstjames.org',
		 timeout => 60,
		 }
		);
	}
 else
 	{
	 $transport = Email::Sender::Transport::SMTP->new
	 	(
		 {
		 host => $email_smtp,
		 port => $email_port,
		 sasl_username => $email_uid,
		 sasl_password => $email_pwd,
		 ssl => $email_use_ssl,
		 helo => 'bgstjames.org',
		 timeout => 60,
		 }
		);
	}

 my $rc = try_to_sendmail( $email, {from=>$email_uid, transport=>$transport});
 print "RC=$rc\n";
 return( !defined( $rc));
}

